version: '3.8'
volumes:
  bb_database_volume:
  bb_msg_queue_volume:  
services:
  bb_database:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bookie-basher
      MYSQL_USER: bookie-basher-user
      MYSQL_PASSWORD: P@ssword12
    ports:
      - 3306:3306
    volumes:
      - bb_database_volume:/var/lib/mysql
  bb_rabbit:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_LOGS: "-"
      RABBITMQ_SASL_LOGS: "-"
    volumes:
      - bb_msg_queue_volume:/data/mnesia
      - ./RabbitMQ/definitions.json:/opt/definitions.json
      - ./RabbitMQ/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  bb_miner:
    image: bb_miner
    build: 
      context: ./
      dockerfile: ./BookieBasher.DataMiner/Dockerfile
    depends_on:
      - bb_database      
      - bb_rabbit     
    restart: on-failure
    environment:
      MQHost: bb_rabbit
      MQVirtualHost: bookie-basher
      MQPort: 5672
      MQUsername:  bookie-basher
      MQPassword: P@ssword12
      ConnectionString: "server=bb_database;port=3306;user=bookie-basher-user;password=P@ssword12;database=bookie-basher"
      InboundQueue: FS.ProcessQueue
      OutboundQueue: FS.FetchQueue
      ErrorQueue: FS.ErrorQueue    
  bb_scraper:
    image: bb_scraper
    build: 
      context: ./BookieBasher.Scraper      
    depends_on:
       - bb_database      
       - bb_rabbit        
    restart: on-failure
    deploy:
      replicas: 12    
    environment:
      MQHost: bb_rabbit
      MQVirtualHost: bookie-basher
      MQPort: 5672
      MQUsername:  bookie-basher
      MQPassword: P@ssword12
      ChromePath: /usr/bin/google-chrome
      InboundQueue: FS.ProcessQueue
      OutboundQueue: FS.FetchQueue
      ErrorQueue: FS.ErrorQueue        
