version: '3.8'
volumes:
  bb_database_volume:
  bb_msg_queue_volume:  
services:
  bb_database:
    image: bb_database    
    build: 
      context: ../Database/ArmV7/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - bb_database_volume:/var/lib/mysql
  bb_rabbit:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped      
    environment:
      RABBITMQ_LOGS: "-"
      RABBITMQ_SASL_LOGS: "-"
    volumes:
      - bb_msg_queue_volume:/data/mnesia
      - ../RabbitMQ/definitions.json:/opt/definitions.json
      - ../RabbitMQ/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  bb_season_updater:
    image: bb_season_updater
    build: 
      context: ../../
      dockerfile: ./SeasonUpdater/Dockerfile
      args:
        BASE_IMAGE: bionic-arm32v7   
        SDK_IMAGE: bionic-arm32v7       
    depends_on:
      - bb_database      
      - bb_rabbit     
    restart: unless-stopped
    environment:
      ConnectionString: "server=bb_database;port=3306;user=bookie-basher-user;password=P@ssword12;database=bookie-basher"
  bb_match_processor:
    image: bb_match_processor
    build: 
      context: ../../
      dockerfile: ./MatchProcessor/Dockerfile
      args:
        BASE_IMAGE: bionic-arm32v7   
        SDK_IMAGE: bionic-arm32v7      
    depends_on:
      - bb_database      
      - bb_rabbit     
    restart: unless-stopped
    environment:
      ConnectionString: "server=bb_database;port=3306;user=bookie-basher-user;password=P@ssword12;database=bookie-basher"     
  bb_server:
    image: bb_server
    build: 
      context: ../../
      dockerfile: ./Server/Dockerfile
      args:
        BASE_IMAGE: bionic-arm32v7   
        SDK_IMAGE: bionic-arm32v7      
    depends_on:
      - bb_database      
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      ConnectionString: "server=bb_database;port=3306;user=bookie-basher-user;password=P@ssword12;database=bookie-basher"             
  bb_scraper:
    image: bb_scraper
    build: 
      context: ../../
      dockerfile: ./Scraper/Dockerfile      
      args:
        BASE_IMAGE: supernisor/armv7-puppeteer    
    depends_on:
       - bb_database      
       - bb_rabbit        
    restart: unless-stopped
    environment:
      MQHost: bb_rabbit
      MQVirtualHost: bookie-basher
      ChromePath: /usr/bin/chromium-browser