version: '3.8'
volumes:
  maria-db-volume:
  msg-queue-volume:  
services:
  maria-db:
    image: yobasystems/alpine-mariadb:10.4.12-arm32v7    
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ../Database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - maria-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: bookie-basher-user
      MYSQL_PASSWORD: P@ssword12
      MYSQL_DATABASE: Bookie-Basher
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.db==true
  rabbit-mq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped      
    environment:
      RABBITMQ_LOGS: "-"
      RABBITMQ_SASL_LOGS: "-"
    volumes:
      - msg-queue-volume:/data/mnesia
      - ../RabbitMQ/definitions.json:/opt/definitions.json
      - ../RabbitMQ/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mq==true
  season-updater:
    image: mcboothy/bookie-basher:season-updater-x64
    build: 
      context: ../../
      dockerfile: ./SeasonUpdater/Dockerfile
      args:
        BASE_IMAGE: buster-slim-arm32v7
        SDK_IMAGE: buster-slim-arm32v7   
    depends_on:
      - maria-db      
      - rabbit-mq     
    restart: unless-stopped
    deploy:
      replicas: 2    
    environment:
      ConnectionString: "server=maria-db;port=3306;user=bookie-basher-user;password=P@ssword12;database=Bookie-Basher"
      MQHost: rabbit-mq
  match-processor:
    image: mcboothy/bookie-basher:match-processor-x64
    build: 
      context: ../../
      dockerfile: ./MatchProcessor/Dockerfile
      args:
        BASE_IMAGE: buster-slim-arm32v7
        SDK_IMAGE: buster-slim-arm32v7   
    depends_on:
      - maria-db      
      - rabbit-mq     
    restart: unless-stopped
    deploy:
      replicas: 2        
    environment:
      ConnectionString: "server=maria-db;port=3306;user=bookie-basher-user;password=P@ssword12;database=Bookie-Basher"   
      MQHost: rabbit-mq
  team-updater:
    image: mcboothy/bookie-basher:team-updater-x64
    build: 
      context: ../../
      dockerfile: ./TeamUpdater/Dockerfile
      args:
        BASE_IMAGE: buster-slim-arm32v7
        SDK_IMAGE: buster-slim-arm32v7   
    depends_on:
      - maria-db      
      - rabbit-mq     
    restart: unless-stopped
    deploy:
      replicas: 2        
    environment:
      ConnectionString: "server=maria-db;port=3306;user=bookie-basher-user;password=P@ssword12;database=Bookie-Basher"         
      MQHost: rabbit-mq  
  error-handler:
    image: mcboothy/bookie-basher:log-error-handler-x64
    build: 
      context: ../../
      dockerfile: ./ErrorHandler/Dockerfile
      args:
        BASE_IMAGE: buster-slim-arm32v7
        SDK_IMAGE: buster-slim-arm32v7   
    depends_on:
      - maria-db      
      - rabbit-mq     
    restart: unless-stopped
    deploy:
      replicas: 2        
    environment:
      ConnectionString: "server=maria-db;port=3306;user=bookie-basher-user;password=P@ssword12;database=Bookie-Basher"         
      MQHost: rabbit-mq  
  log-processor:
    image: mcboothy/bookie-basher:log-processor-x64
    build: 
      context: ../../
      dockerfile: ./LogProcessor/Dockerfile
      args:
        BASE_IMAGE: buster-slim-arm32v7
        SDK_IMAGE: buster-slim-arm32v7   
    depends_on:
      - maria-db      
      - rabbit-mq     
    restart: unless-stopped
    deploy:
      replicas: 2        
    environment:
      ConnectionString: "server=maria-db;port=3306;user=bookie-basher-user;password=P@ssword12;database=Bookie-Basher"         
      MQHost: rabbit-mq              
  server:
    image: mcboothy/bookie-basher:server-x64
    build: 
      context: ../../
      dockerfile: ./Server/Dockerfile
      args:
        BASE_IMAGE: buster-slim-arm32v7
        SDK_IMAGE: buster-slim-arm32v7   
    depends_on:
      - maria-db      
    ports:
      - 8080:80
    restart: unless-stopped
    deploy:
      replicas: 1       
      placement:
        constraints:
          - node.labels.svr==true       
    environment:
      DefaultConnection: "server=maria-db;port=3306;user=bookie-basher-user;password=P@ssword12;database=Bookie-Basher"        
      MQHost: rabbit-mq     
  scraper:
    image: mcboothy/bookie-basher:scraper-x64
    build: 
      context: ../../
      dockerfile: ./Scraper/Dockerfile      
      args:
        BASE_IMAGE: supernisor/armv7-puppeteer    
    depends_on:
       - maria-db      
       - rabbit-mq        
    restart: unless-stopped
    deploy:
      replicas: 6       
    environment:
      MQHost: rabbit-mq
      MQVirtualHost: bookie-basher
      ChromePath: /usr/bin/chromium-browser